### PR TITLE
Separare inport and outport device tabs and "bang" support

### LINKED ISSUE #235: inport messages not working
running the latest `develop` at `0c4ef7ee6f11c0984de39c0ea3ff410b545bf625`

send and load this patcher

<pre><code>
----------begin_max5_patcher----------
2200.3oc6a01aaiiD9y1+JHzWxc.IFV1INNKNbX60jEvGtKInoc+RQQ.sDcL
2UlTGEUhSWz629NjTuR8lShR21j9g1jvWFQ97LynYn37GCG3rjukD4f9IzGQ
CF7GCGLP2jpgAI+8.mM3sdA3H8vbXj63K+Mm8MccKVvvaH5dDrk7+eZGRxVY
0VCwRu0T1MWKHdRyS8H24iFuOx08P0ONbr5+mLYzXzmRlC0WKG3gdfapbXwa
3wx.hTulbSZ0zj79PhQzNAzH3o7o7IQY1yQs7tkHhnbl9w3NBVGG3wYRAOXj
6zRqbhHAXRPlANqnAjBSOQpCbvggEZdPgonfyeiqEzI6m0DkYZZbVSBxszz4
eXVqXAfeR.7hEFPe6rCcxEC2mHXwT8Rwz3WFltjzTnhrhBwd4LV5rcxoj4i0
TxwylpYlYyzjxIGOOmUF33SVgiCjWuBfpLUf+CVlKvaDT+H5mSHC2izB6nhx
PRABSOwXl928ylbI8xhvWQ8yRs2ldZYUxPAkIQq37h8Vip4gSMplFb3HsB5j
oE1.VpmSKJuxpniK2SE8vLcwqiYz+WLIQp5U50UjsdfQDAEGTqLxn5bg3jNj
uLbX5ureuAsEcCrgynRPatVjGKvaP0LhZP+oFXexXW0OlOqKzeRyn+jB8TwI
gy9v+JIzRDzDKvkxVwKfQE.IXhDhezBVjDy7HKRFXA1QY+di1DrnDJJBETFD
SJ0co9AQHkhKDWJ3g1RWYURugDYv5KUXMQRDHiHsFnw7EVOVaRMpFgCnXaEW
8CW0dpgYQPS0YDfq3kFKZq0ErnwdqS6br8iSqWT21gDBJDXIwuloI4wfK455
Qyd0HtTVWwvKIh5gjeMk.bF6Tn+LGoITMWrA.iOS76MB6JhzPUnbgOB4zKTy
th+i+ph+MCuBRjQBOUP8cJAgL9cjbDE77.dMq0jnWfV2mYnMCBWhY2rS5m8A
JddlzLPYtakQeOpeZdGvSRAM80c6FxNoYjEjChuBIWSxg1V8U69shu5dVgN5
9MK4AVa8.7RRf0qyTPl0v1fY9Pnmh6KD4acrFA309f09PDAgYHk3HB0VFApT
gwRmWnbiNQplXly.T.oeqYjshKrhBv2yE9lLml0Ly.QbQ2zOjy+0HpmhOd0x
w4aeZYWCioIlKAo5f0bak09JxXt0vXWrxjzQs6juyrx9qmNwa6MiPindZFg3
suXLBcal0R.81YsIsxZeEYr1LBqcm7hzH7YjNIaC4LBS1Gb5Ud3.hgQiPoBF
x+I39WpQp7TouyRQ+14uial+hjjvn9f7NkdK0mnyLvDcIj8JjBKFY1iprFfk
km.BJFYdnup4zleu3U0.N1D57lIzjgddOkw2omc46N6su48mc5OgT4Qn32.9
c.g5AjBZujGmJAy8.FGXVr+2GLqaemy2oFnvjwWmDTekR9aPa3BBR.3tBPPJ
4hVwEkyQGnFcJfagemgCPu67+0EHUN5jWrYAVKaUwNb2XyNhQ8vlY6XFU1Oz
rY+nNVPeB3GktzXLpd.UNRleP2OT59CJdpCZ9nloYI+wbDlMS2ukytkHjQv6
OAK6.6ywTe3vPu4OTkI+lQNuNOss2yQENyWHnHAIR+0n6fPG2LgtRv27rQor
5NfZc3RJRE6IiqR4uV41eAHhGE6dRyja1Xdpb5EJAob1d2Zp25ruWiE0Egti
FDf.G1QPr5pviQbFJ4NZ.QSg8GgduJtYsz7.G2vP0GVK0CZLwyO76+s8VQEQ
x8.e69n8Bvvu92ec6Ou4vneGvQp.izTTWNBlzY3ZOWpLYpJIJIQq42ghC0u.
GoNHa061gTfKLvenr7HUVNnyf81IkkosjMMg4S6oH9tBj0ywW.9aO1aIuatS
Jpr+KjxrBpVzcDbsDmtmLnm95.KNcAJ4F4E.VnIG+A7t8jFgH0oQ4lyidUcN
HEN4QEN81bb5b8vG0kwWaeTNhD2OoZ8uu5hy0ATCSAB4HRJnraz7GFLHgeU8
n7wRrNQ63HBZ485DvTGZoPMEOtO4GYZUOwmfccwzG210EI7AdkaZ4.t3P33R
D122XXlkekNgZ8iA8w7SACc.5CWcF5mS5Yb5Yd8oQuTO0qcw67JbPTam4U+Q
WuoEdZzOdAYC1bKXdAw9D3cjnKMTQGFek+rqCqmWcnrvXYo68bUhM6l1VWHL
cbn48x0CcMut6NkO262S.8xpscuQruLkOxszNcAJaZYVRm0w7AWdESDO1cyt
eSA2MhXMIHL+lrq8FT59TW3yOWsWq6Aek94gpaukUkWnuD1lZ2XgwA+wGM8j
CmehaoaxM3zhA65KMm4vhKJuQJZUatS9jsRA9ZkSY5xXY4a.dw6PdgKBkprK
FV+GF1sbWomIdoXDp3Cpb5Z1e1jxyM+8Kk104xpz4DTyg6UVb1mla4dyRUvZ
GW39nXsgSiLsrbx9zq1HWx09yZzERszsElqTEYTSsK7.qFCsV3yZ0XjUtEva
Sffm2gJcIoVKbcmn9wL2tp0B2lq0B2Vq0hlqyhwOZClLUgckCMvx0U1HOLhz
Hk5Xx7BbBTqapJlzrfp+5o3HdrvKE1RVonx7gO3ykxvxjhD6iYEgj03xrYGu
SZcOWKrIMuvbaED4B5MfcZREQgkGLY9QFXOkmMEbvhBUlSZ84s3hzVUQkVdR
FsyG5rTZBJkROHrUh8DS8NTol+xCbz1ABDj6YItmxK9OvIADLsNI4hp1IvS1
ZAGK4Q3aKFWsi5u8U51fwcMVOoqTdnjtg94LRx4hLSAmrWbeMgYG1tSbbBS3
Na4XO7pkG35MCefq6pwGLW8mGOa9zUyc878lehEMYVaYKpVVd5HF3qpBj4qM
JSUfj1YUTX.Ab1M0VbpkF0FtuprIqf+Icyi7tNSH+ijnw9m0Inn0f6ftedod
CmZQoCS++DUe6RHUg.VkNpUYiVsjQatbQsKUTMEUWIhpdGzvuL7OA5ObMyC
-----------end_max5_patcher-----------
</code></pre>

go to the node and try sending `0.2` and notice that the `monitor` param doesn't change.. but you can updated it via OSC:

```
oscsend localhost 1234 /rnbo/inst/0/messages/in/foo f 0.5
```

also.. you can't send empty messages (bangs), you get an error popup... to get all of what the port interface allows for, you should be able to send empty, a single number or a list of numbers

### PR DESCRIPTION
**Pull request by fde31**
fixes #235

### CODE REVIEW

File: src/actions/patchers.ts [hunk 1]
```diff
@@ -649,28 +649,62 @@ export const setInitialPresetOnRemoteInstance = (instance: PatcherInstanceRecord
...
-			address: `/rnbo/inst/${instance.id}/messages/in/${inportId}`,
-			args: values
-		};
-		oscQueryBridge.sendPacket(writePacket(message));
+export const sendInstanceInportBang = (instance: PatcherInstanceRecord, port: MessagePortRecord): AppThunk =>
+	(dispatch) => {
+		try {
+			const message = {
+				address: port.path,
+				args: [{ type: "f", value: "" }]
```
Comment (fde31) [inline src/actions/patchers.ts:697]: @x37v is this the expected OSC message for a bang or what would be expected?

Comment (x37v) [reply src/actions/patchers.ts:697]: just empty args

Comment (fde31) [reply src/actions/patchers.ts]: adjusted in a2240b2d7c8f838a227738587b65849371e4047d

File: src/actions/patchers.ts [hunk 2]
```diff
@@ -649,28 +649,62 @@ export const setInitialPresetOnRemoteInstance = (instance: PatcherInstanceRecord
...
+
+			const dialogResult = await showTextInputDialog({
+				text: `Send Inport message to ${port.name}`,
+				actions: {
+					confirm: { label: "Send" }
+				},
+				validate: (value: string) => {
+					if (!value.length) return "Please provide a value";
+					const values = value.trim().replaceAll(",", ".").split(" ");
+					if (values.find(v => isNaN(parseFloat(v)))) return "Please provide a single or multiple numbers separated by a space";
```
Comment (x37v) [inline src/actions/patchers.ts:664]: this might be better worded `please provide a number or multiple numbers separated by spaces`

**Review by x37v — APPROVED** [review]
one little comment about wording but looks great otherwise
